// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3PSfx2iYntmJQ9wpbyJjhwVhCxWlLU0',
    appId: '1:7226658138:android:c8f1a6168eb4ea733c7763',
    messagingSenderId: '7226658138',
    projectId: 'moneybag-a6237',
    storageBucket: 'moneybag-a6237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoh1aSqJehEWxiYLtMdEI4Cql-7Gez2z0',
    appId: '1:7226658138:ios:2210b9f2535790f23c7763',
    messagingSenderId: '7226658138',
    projectId: 'moneybag-a6237',
    storageBucket: 'moneybag-a6237.appspot.com',
    iosClientId: '7226658138-1cn7it47di0vrvrnrmka6sklererve8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
